name: "Cargo Build"

on:
  push:
    branches: [ "bevy" ]
  pull_request:
    branches: [ "bevy" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: ConorMacBride/install-package@v1
      with:
        apt: pkg-config libasound2-dev libudev-dev
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: actions-rs/cargo@v1
      with:
        command: test
