name: "Cargo Build"

on:
  push:
    branches: [ "bevy" ]
  pull_request:
    branches: [ "bevy" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu"] #["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"]
    steps:
      - uses: actions/checkout@v3
     #- uses: ConorMacBride/install-package@v1
     #  with:
     #    apt: pkg-config libasound2-dev libudev-dev mingw-w64
      - uses: dtolnay/rust-toolchain@stable
      - name: "Build project"
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
      - name: "Copy linux files"
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cp -r client/assets/ assets/
          mv target/${{ matrix.target }}/release/client client
          mv target/${{ matrix.target }}/release/server server
      - name: "Copy windows files"
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          cp -r client/assets/ assets/
          mv target/${{ matrix.target }}/release/client.exe client.exe
          mv target/${{ matrix.target }}/release/server.exe server.exe
      - name: "Upload linux"
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: |
            assets/
            client
            server
      - name: "Upload windows"
        if: matrix.target == 'x86_64-pc-windows-gnu'
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: |
            assets/
            client.exe
            server.exe
