name: "Cargo Build"

on:
  push:
    branches: [ "bevy" ]
  pull_request:
    branches: [ "bevy" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu"] #["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"]
    steps:
      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: DD-MM-YYYY-hh-mm-ss
          utcOffset: "+02:00"
      - uses: actions/checkout@v3
     #- uses: ConorMacBride/install-package@v1
     #  with:
     #    apt: pkg-config libasound2-dev libudev-dev mingw-w64
      - uses: dtolnay/rust-toolchain@stable
      - name: "Build project"
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
      - name: "Copy linux files"
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cp -r client/assets/ assets/
          mv target/${{ matrix.target }}/release/client game-client
          mv target/${{ matrix.target }}/release/server game-server
          zip -9 -r ${{ steps.current-time.outputs.formattedTime }}.zip assets/ game-client game-server
      - name: "Copy windows files"
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          cp -r client/assets/ assets/
          mv target/${{ matrix.target }}/release/client.exe game-client.exe
          mv target/${{ matrix.target }}/release/server.exe game-server.exe
          zip -9 -r ${{ steps.current-time.outputs.formattedTime }}.zip assets/ game-client.exe game-server.exe
      - name: "Upload file"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "Build finished for ${{ matrix.target }}(${{ steps.current-time.outputs.readableTime }})"
          file: "./${{ steps.current-time.outputs.formattedTime }}.zip"
